version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    volumes:
      - django_static:/app/static/
      - django_media:/app/media/

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    environment:
      - BACKEND_ADDR="http://backend:8000/"
    volumes:
      - frontend_dist:/app/public/build/
    links:
      - backend

  nginx:
    build:
      context: .
      dockerfile: docker/Dockerfile.nginx
    volumes:
      - frontend_dist:/frontend/
      - django_static:/static/
      - django_media:/media/
    ports:
      - "80:80"
    links:
      - backend

volumes:
  django_static:
  django_media:
  frontend_dist:
